config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  namespace :admin do
    resources :users
  end

  resources :tasks do
    post :import, on: :collection
  end

  get    '/login',  to: 'sessions#new'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    '/signup', to: 'users#new'

  # letter opener web
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  # has_one_attached :image # 添付画像は一つ
  has_many_attached :images # 複数の添付画像

  # activestorage-validator による添付画像の検証
  validates :images,
    content_type: %i(gif png jpg jpeg),                        # 画像の種類
    size: { less_than_or_equal_to: 5.megabytes },              # ファイルサイズ
    dimension: { width: { max: 2000 }, height: { max: 2000 } } # 画像の大きさ

  # before_validation :set_nameless_name

  validates :name, presence: true
  validates :name, length: { maximum: 30 }
  validate :validate_name_not_including_comma

  belongs_to :user

  scope :recent, -> { order(created_at: :desc) }

  class << self
    # モデル側で検索対象のカラムを指定する。
    # (Strong Parametersのメンテナンスが大変なため)
    def ransackable_attributes(auth_object = nil)
      %w[name created_at]
    end

    def ransackable_associations(auth_object = nil)
      []
    end

    def csv_attributes
      %w(name description created_at updated_at)
    end

    def generate_csv
      CSV.generate(headers: true) do |csv|
        csv << csv_attributes
        all.each do |task|
          csv << csv_attributes.map{ |attr| task.send(attr) }
        end
      end
    end

    def import(file)
      CSV.foreach(file.path, headers: true) do |row|
        task = new # Task.new と ほぼ同意
        task.attributes = row.to_hash.slice(*csv_attributes)
        task.save!
      end
    end
  end

  private

  # def set_nameless_name
  #   self.name = '名前無し' if name.blank?
  # end

  def validate_name_not_including_comma
    errors.add(:name, 'にカンマを含めないでください') if name&.include?(',')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true

  has_many :tasks
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  def index
    @user = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to admin_users_path, notice: "利用者「#{@user.name}」を作成しました"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admin_user_path(@user), notice: "利用者「#{@user.name}」を更新しました"
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to admin_users_path, notice:  "利用者「#{@user.name}」を削除しました"
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
  end

  def require_admin
    redirect_to root_path, notice: '管理者権限が必要です' unless current_user.admin?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :success, :info, :warning, :error
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def login_required
    redirect_to login_path unless current_user
  end
end

app/controllers/errors_controller.rb
# https://qiita.com/mknstone/items/d027070ed0d004ffc993
class ErrorsController < ApplicationController
  layout 'application'

  rescue_from StandardError,                  with: :internal_server_error
  rescue_from ActionController::RoutingError, with: :not_found
  rescue_from ActiveRecord::RecordNotFound,   with: :not_found

  def show
    raise
  end

  def not_found(exception = nil)
    render template: 'application/not_found', status: 404
  end

  def internal_server_error(exception = nil)
    render template: 'application/internal_server_error', status: 500
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required

  def new
  end

  def create
    user = User.find_by(email: session_params[:email])

    if user&.authenticate(session_params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました'
    else
      flash[:error] = 'メールアドレス または パスワードが異なります'
      render :new
    end
  end

  def destroy
    # user_idのみの削除
    # session.delete(:user_id)
    # セッション内のデータを全て削除
    reset_session
    redirect_to root_path, notice: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  include Pagy::Backend

  def index
    # @tasks = Task.all
    # @tasks = current_user.tasks.recent

    @q = current_user.tasks.ransack(params[:q])
    # @tasks = @q.result(distinct: true)
    # @pagy, @tasks = pagy(@q.result(distinct: true), size: [1, 2, 2, 1])
    @pagy, @tasks = pagy(@q.result(distinct: true))

    respond_to do |format|
      format.html
      format.csv { send_data @tasks.generate_csv, filename: "tasks-#{l(Date.current)}.csv" }
    end
  end

  def show
    # # @task = Task.find(params[:id])
    # @task = current_user.tasks.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = current_user.tasks.new(task_params)

    if @task.save
      # タスク作成した旨、メール送信する
      TaskMailer.creation_email(@task).deliver_now

      # notice以外に、success, info, warning, errorも使用可能
      redirect_to @task, notice: "タスク「#{@task.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    # # @task = Task.find(params[:id])
    # @task = current_user.tasks.find(params[:id])
  end

  def update
    # # task = Task.find(params[:id])
    # task = current_user.tasks.find(params[:id])

    # 画像の削除処理
    params[:task][:image_ids]&.each do |image_id|
      @task.images.find(image_id).purge_later
      ActiveStorage::Blob.unattached.find_each(&:purge)
    end

    if @task.update(task_params)
      # notice以外に、success, info, warning, errorも使用可能
      redirect_to tasks_url, notice: "タスク「#{@task.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    # # task = Task.find(params[:id])
    # task = current_user.tasks.find(params[:id])
    @task.destroy
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を削除しました。"
  end

   def import
    current_user.tasks.import(params[:file])
    redirect_to tasks_url, notice: 'タスクを追加しました'
  end

  private

  def task_params
    # params.require(:task).permit(:name, :description, :image)
    params.require(:task).permit(:name, :description, images:[])
  end

  def set_task
    @task = current_user.tasks.find(params[:id])
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  skip_before_action :login_required

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def full_title(page_title = nil)
    base_title = "株式会社蓮華草"
    base_title = "【開発】#{base_title}" if Rails.env.development?
    page_title.blank? ? base_title : "#{page_title} | #{base_title}"
  end
end

app/views/admin/users/_form.html.slim
- if user.errors.present?
  ul#error_explanation
    - user.errors.full_messages.each do |message|
      li = message

= form_with model: [:admin, user], class: 'ui form', local: true do |f|
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :password
    = f.password_field :password
  .field
    = f.label :password_confirmation
    = f.password_field :password_confirmation
  .field
    = f.label :admin
      = f.check_box :admin
      | &nbsp; 管理者権限
  .field
    = f.submit nil, class: 'ui primary button'

app/views/admin/users/edit.html.slim
h1  利用者編輯

= render partial: 'form', locals: { user: @user }

app/views/admin/users/index.html.slim
h1 利用者一覧

= link_to '新規登録', new_admin_user_path, class: 'ui primary button'

table.ui.blue.striped.table
  thead
    th = User.human_attribute_name :name
    th = User.human_attribute_name :email
    th = User.human_attribute_name :admin
    th = User.human_attribute_name :created_at
    th = User.human_attribute_name :updated_at
    th
  tbody
    - @user.each do |user|
      tr
        / td = link_to user.name, admin_user_path(user)
        td = link_to user.name, [:admin, user]
        td = user.email
        td = user.admin? ? '有り' : '無し'
        td = user.created_at
        td = user.updated_at
        td
          / = link_to '編輯', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
          = link_to '編輯', [:edit, :admin, user], class: 'ui yellow button'
          = link_to '削除', admin_user_path(user), method: :delete, data: { confirm: '本当に削除してよろしいですか' }, class: 'ui red button'

app/views/admin/users/new.html.slim
h1  利用者登録

= render partial: 'form', locals: { user: @user }

app/views/admin/users/show.html.slim
h1  利用者詳細

= link_to '一覧', admin_users_path, class: 'ui right floated primary tertiary button'

table.ui.blue.striped.table
  tbody
    tr
      th = User.human_attribute_name :name
      td = @user.name
    tr
      th = User.human_attribute_name :email
      td = @user.email
    tr
      th = User.human_attribute_name :admin
      td = @user.admin? ? '有り' : '無し'
    tr
      th = User.human_attribute_name :created_at
      td = @user.created_at
    tr
      th = User.human_attribute_name :updated_at
      td = @user.updated_at

/ = link_to '編輯', edit_admin_user_path(user), class: 'btn btn-primary mr-3'
= link_to '編輯', [:edit, :admin, @user], class: 'ui yellow button'
= link_to '削除', admin_user_path(@user), method: :delete, data: { confirm: '本当に削除してよろしいですか' }, class: 'ui red button'

app/views/application/internal_server_error.html.slim
.ui.error.message
  i.close.icon
  .header
    | 申し訳ありませんが、何か不具合が起きました
    br
    | (500 Internal Server Error)
  ul.list
    li
      | 管理者の対応をお待ちください

app/views/application/not_found.html.slim
.ui.error.message
  i.close.icon
  .header
    | お探しのページは存在しません
    br
    | (404 Not Found)
  ul.list
    li
      | アドレスが間違っているか ページが移動した可能性があります

app/views/layouts/_footer.slim
footer.ui.bottom.menu
  h4
    | Copyright © 令和四年 株式会社蓮華草 All rights reserved.

app/views/layouts/_header.slim
header.ui.top.menu.mobile.only
  .ui.container
    #js-sidebar.item
      i.icon.large.grey.content
    .logo_mark
      = link_to root_path do
        = image_tag('renge.jpg', alt: 'logo')
        h1
          | Taskleaf
          = semantic_icon('leaf')


header.ui.top.fixed.menu.computer.only
  .ui.container
    .logo_mark
      = link_to root_path do
        = image_tag('renge.jpg', alt: 'logo')
        h1
          | Taskleaf
          = semantic_icon('leaf')

    .right.menu
      .ui.dropdown.item
        | 会社案内
        i.dropdown.icon
        .menu
          = link_to '経営理念', root_path, class: 'ui item'
          = link_to '会社沿革', root_path, class: 'ui item'
          = link_to '会社概要', root_path, class: 'ui item'
          .divider
          = link_to '採用情報', root_path, class: 'ui item'

      = link_to 'お問い合わせ', root_path, class: 'ui item'

      .item
        form class="ui form" action="/tasks"
          .ui.icon.input
            .ui.icon.input
              input placeholder="検索" type="text" name="q[name_cont]" id="q_name_cont"
                i.search.link.icon
            button.ui.primary.basic.small.button type="submit"
              | 検索
      .item
        - if current_user
          = link_to 'タスク一覧', tasks_path, class: 'ui primary tertiary button'
          - if current_user.admin?
              = link_to '利用者一覧', admin_users_path, class: 'ui primary tertiary button'
          = link_to 'ログアウト', logout_path, method: :delete, class: 'ui basic primary button'
        - else
          = link_to 'ログイン', login_path, class: 'ui primary button mr-3'
          = link_to '利用者登録', signup_path, class: 'ui positive button'

app/views/layouts/_sidebar.slim
= link_to root_path, class: 'active item' do
  | Taskleaf
  = semantic_icon 'leaf'

= link_to root_path, class: 'item' do
  | 会社案内
  = semantic_icon 'building outline'

= link_to root_path, class: 'item' do
  = semantic_icon 'paper plane'
  | お問い合わせ

- if current_user
  = link_to tasks_path, class: 'item'
    | タスク一覧
    = semantic_icon 'tasks'
  - if current_user.admin?
      = link_to admin_users_path, class: 'item'
        | 利用者一覧
        = semantic_icon 'user icon'
  = link_to logout_path, method: :delete, class: 'item'
    | ログアウト
    = semantic_icon 'sign out alternate'
- else
  = link_to login_path, class: 'item'
    | ログイン
    = semantic_icon 'sign in alternate'
  = link_to signup_path, class: 'item'
    | 利用者登録
    = semantic_icon 'user plus'

app/views/layouts/application.html.slim
doctype html
html
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width"
    meta name="description" content="現場で使える Ruby on Rails 速習実践ガイド による
    タスク管理アプリ Taskleaf"
    title = full_title(yield(:page_title))

    / ファビコンの指定 https://ao-system.net/favicongenerator/
    = favicon_link_tag 'favicon.ico'
    = favicon_link_tag 'apple-touch-icon-180x180.png',
                        rel:   'apple-touch-icon',
                        sizes: '180x180',
                        type:  'image/png'

    / cross-site request forgeries
    = csrf_meta_tags
    / Content Security Policy
    = csp_meta_tag

    / sprocket管理下のcssを読み込む
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    / webpack管理下のjsを読み込む
    / = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    / sprocket管理下のjsを読み込む
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  body
    / iPhone用 サイドバーメニュー
    .ui.sidebar.green.vertical.menu
      == render 'layouts/sidebar'

    / コンテンツ本体
    .pusher
      / ヘッダー
      == render 'layouts/header'

      / メイン
      main.ui.container
        / flashメッセージを表示
        = semantic_flash
        = yield

      / フッター
      == render 'layouts/footer'

      / 開発中のデバッグ情報を表示
      - if Rails.env.development?
        .ui.container
          = debug(params)

app/views/tasks/_form.slim
- if task.errors.present?
    ul#error_explanation
      - task.errors.full_messages.each do |message|
        li = message

= form_with model: task, class: 'ui form', local: true do |f|
  .field
    = f.label :name
    = f.text_field :name, required: true
  .field
    = f.label :description
    = f.text_area :description

  .field
    = f.label :images
    - if task.images.attached?# && task.images.blobs&.persisted?
      .ui.cards
        - task.images.each do |image|
          .card
            .image
              = image_tag image
              / = image_tag task.image.variant(resize_to_limit: [300, 300])
            .extra.content
              .ui.checkbox
                = f.check_box :image_ids, { multiple: true }, image.id, false
                = f.label "image_ids_#{image.id}"
                  | &nbsp; 画像を削除する


    = f.file_field :images, accept: 'image/jpg, image/jpeg, image/png, image/gif', multiple: true, id: 'embed_file_input'

  .ui.fluid.action.input.mb-3
    input#selected_filenames_display_area disabled="disabled" placeholder="画像ファイルはありません" type="text"
    label.ui.small.teal.left.floated.button for="embed_file_input"
      = semantic_icon('upload')
      | 画像選択

  = f.submit nil, class: 'ui primary button'

css:
  input[type="file"] {
    display: none;
  }
  #selected_filenames_display_area {
    opacity: 1;
  }

javascript:
  // https://hakuhin.jp/js/input_file.html#INPUT_FILE_ON_CHANGE を洗練化

  // "embed_file_input" という ID属性の要素を取得する。(画像選択ボタン)
  const input_files = document.getElementById("embed_file_input");
  // 選択ファイル名表示領域
  const selected_filenames_display_area = document.getElementById("selected_filenames_display_area");

  // 値が変化した時(ファイル選択時)に実行されるイベント
  input_files.onchange = function() {
    // FileList オブジェクトを取得する
    let file_lists = input_files.files;
    // 画像ファイル名格納用の配列
    let file_names = []
    for (let i = 0; i < file_lists.length; i++) {
      // File オブジェクトより、画像ファイル名を取得する
      file_names.push(file_lists[i].name)
    }
    // 選択ファイル名表示領域に、画像ファイル名を書き出す
    selected_filenames_display_area.value = file_names.join(', ')
  }

app/views/tasks/edit.html.slim
h1 タスクの編輯

= link_to '一覧', tasks_path, class: 'ui right floated primary tertiary button'

= render partial: 'form', locals: { task: @task }

app/views/tasks/index.html.slim
h1 タスク一覧

.ui.segment
  p
    | 登録したタスクの検索ができます。

  / ransack による検査機能
  = search_form_for @q, class: 'ui form' do |f|
    .field
      / 名称に○○を含む name_cont
      = f.label :name_cont, '名称'
      = f.search_field :name_cont
    .field
      = f.label :created_at_gteq, '登録日時'
      .ui.calendar#datetime_calendar
        .ui.input.left.icon
          i.calendar.icon
          / = f.search_field :created_at_gteq, placeholder: "DateTime"
          input type="search" name="q[created_at_gteq]"
    .field
      = f.submit class: 'ui primary basic button'

= link_to '新規登録する', new_task_path, class: 'ui primary button'

== pagy_semantic_nav(@pagy)

table.ui.green.striped.table
  thead
    tr
      / th = Task.human_attribute_name(:name)
      th = sort_link(@q, :name, [:name, "created_at desc"])
      th = Task.human_attribute_name(:created_at)
      th = Task.human_attribute_name(:updated_at)
      th
  tbody
    - @tasks.each do |task|
      tr
        td = link_to task.name, task
        td = l task.created_at, format: :short
        td = l task.updated_at, format: :short
        td
          = link_to '編輯', edit_task_path(task), class: 'ui yellow button'
          = link_to '削除', task, method: :delete, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか?" }, class: 'ui red button'


.ui.segment
  = link_to 'CSV形式でダウンロードする', tasks_path(format: :csv), class: 'ui primary button'
  hr.m-4
  = form_tag import_tasks_path, multipart: true do
    = file_field_tag :file, class: 'm-3', style: 'width: 90%;'
    br
    = submit_tag "CSV形式のファイルから取り込む", class: 'ui primary button'

app/views/tasks/new.html.slim
h1 タスクの新規登録

= link_to '一覧', tasks_path, class: 'ui right floated primary tertiary button'

= render partial: 'form', locals: { task: @task }

app/views/tasks/show.html.slim
h1 タスクの詳細

= link_to '一覧', tasks_path, class: 'ui right floated primary tertiary button'

table.ui.green.striped.table
  tbody
    tr
      th = Task.human_attribute_name(:id)
      td = @task.id
    tr
      th = Task.human_attribute_name(:name)
      td = @task.name
    tr
      th = Task.human_attribute_name(:description)
      td = auto_link(simple_format(h(@task.description), {}, sanitaize: false, wrapper_tag: :div))
    tr
      th = Task.human_attribute_name(:images)
      td
        - if @task.images.attached?# && task.images.blobs&.persisted?
          .ui.cards
            - @task.images.each do |image|
              .card
                .image
                  = image_tag image
                  / p 縮小して少し回転
                  / = image_tag image.variant(resize_to_fit: [200, 200], rotate: 10).processed

    tr
      th = Task.human_attribute_name(:created_at)
      td = @task.created_at
    tr
      th = Task.human_attribute_name(:updated_at)
      td = @task.updated_at

= link_to '編輯', edit_task_path(@task), class: 'ui yellow button'
= link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか?" }, class: 'ui red button'

app/views/welcome/index.html.slim
- provide :page_title, 'ようこそ'

h1.ui.header
  | 蓮華草へ ようこそ!!

h2
  | 「春の小川」
  small
    | 高野辰之作詞・岡野貞一作曲
p
  pre
    code
      |
        春の小川は　さらさら行くよ
        岸のすみれや　れんげの花に
        すがたやさしく　色うつくしく
        咲けよ咲けよと　ささやきながら

        春の小川は　さらさら行くよ
        えびやめだかや　こぶなのむれに
        今日も一日　ひなたでおよぎ
        遊べ遊べと　ささやきながら

= image_tag "renge.jpg"